### ISSUE TITLE
Sprint 2 Checklist 

### ISSUE THREAD

**Issue by PetiaPav** [Franck851/SOEN341#37]
## Grading Scheme
*Planning:*
- [x] Done enough work
- [x] Story descriptions, points, risk, priority
- [x] Task breakdown for every story
- [x] Assigned to individuals (workload balance)
- [x] Plan for next release
- [x] Frequent meetings (scrum) with meeting minutes available

*Repo:*
- [x] Commit logs descriptive and everything referenced
- [x] Discussion and reviews on github items

*Misc:*
- [x] Show up in tutorials meeting with TA

*Other:*
- [x] Completed everything that was scheduled for this sprint
- [x] Backend for login page
- [x] Voting System
- [x] SQL and server setup
- [x] Backend for home feed and Q&A section
- [x] Improve user section
- [x] Linked to Travis CI with empty tests (No need to have tests ready)
