### ISSUE TITLE
Checklist for Sprint 3 grading scheme

### ISSUE THREAD

**Issue by PetiaPav** [Franck851/SOEN341#52]
## Tasks/Criteria

- [x] Done enough work
----------------------------------------------
- [x] Story description
- [x] Points
- [x] Risk
- [x] Priority
- [x] Burndown chart
- [x] Task breakdown for every story
- [x] Workload balance
----------------------------------------------
- [x] Planning for next sprint
- [x] Frequent meetings (scrum) with meeting minutes available
- [x] Architecture (block diagram being consistent with the code
- [x] Quality of code with coding style enforced
- [x] Commit logs descriptive
- [x] Everything referenced
- [x] Discussion
- [x] Review on github items
- [x] Continuous integration with testing executed for every commit
- [x] Acceptance testing for every user story (even for the US in prior sprints)
- [x] Show up in tutorials meeting with TA
