### ISSUE TITLE
Sprint 4 Grading Checklist 

### ISSUE THREAD

**Issue by PetiaPav** [Franck851/SOEN341#58]
## Tasks/Criteria 

- [x] Done enough work
- [x] Have new stories or only clean up work
- [x] Enforcement of planning
- [x] Frequent meetings
- [x] Directory and package structure
- [x] Quality of code
- [x] Coding style enforced
- [x] Commit logs descriptive
- [x] Everything referenced
- [x] Discussion and review on github items
- [x] Continuous integration with testing executed for every commit
- [x] Acceptance testing for every user story
- [x] Show up in tutorials meeting with TA
